version: '3'

services:
  mechazone-frontend:
    build:
      context: .
      target: frontend
    ports:
      - "3000:3000"

  mechazone-backend:
    build:
      context: .
      target: backend
    ports:
      - "5000:5000"
    depends_on:
      - mechazone-frontend