version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    depends_on:
      - sql-server
    environment:
      CONNECTION_STRING: "Server=tcp:eu-az-sql-serv1.database.windows.net,1433;Initial Catalog=d9zkgftdim6prd0;Persist Security Info=False;User ID=ut7xwfa4xede5b2;Password=cEYw6IHcSCliHUX&vXdsynEDC;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"

  sql-server:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "cEYw6IHcSCliHUX&vXdsynEDC"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"