version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    depends_on:
      - sql-server
    environment:
      DB_USER_ID: "ut7xwfa4xede5b2"
      DB_PASSWORD: "cEYw6IHcSCliHUX&vXdsynEDC"
      DB_SERVER: "frontend"  
      DB_DATABASE: "d9zkgftdim6prd0"
      DB_DRIVER: "ODBC+Driver+17+for+SQL+Server"

  sql-server:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "cEYw6IHcSCliHUX&vXdsynEDC"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"