version: 2.1
orbs:
  node: circleci/node@5.1.0

jobs:
  test-frontend:
    docker:
      - image: circleci/node:16.14

    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install Node.js Dependencies
          command: npm install --legacy-peer-deps
      - run:
          name: Run Frontend Tests
          command: npm test

  build-frontend:
    docker:
      - image: circleci/node:16.14

    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install Node.js Dependencies
          command: npm install --legacy-peer-deps
      - run:
          name: run Frontend
          command: npm start

  test-backend:
    docker:
      - image: python:3.8

    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            apt-get update && apt-get install -y unixodbc-dev
            pip install -r requirements.txt
      - run:
          name: Run Backend Tests
          command: pytest

  start-backend:
    docker:
      - image: python:3.8

    steps:
      - checkout
      - run:
          name: Start Backend
          command: |
            cd mechazone/my-react/src/Services
            python Api.py &

workflows:
  version: 2
  test:
    jobs:
      - test-frontend
      - test-backend:
          requires:
            - test-frontend
      - start-backend
