version: 2.1
orbs:
  node: circleci/node@5.1.0

jobs:
  test:
    executor: node/default
    working_directory: /home/circleci/project/my-react
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install Node.js Dependencies
          command: npm install --legacy-peer-deps
      - run:
          name: Run Frontend Tests
          command: npm test
      - run:
          name: Start Frontend Server
          command: npm start
          background: true

workflows:
  version: 2
  test_my_app:
    jobs:
      - test
