version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.17
      - image: circleci/python:3.9

    working_directory: ~/my-react

    steps:
      - checkout

      # Node.js Build and Test
      - run:
          name: Install Node.js Dependencies
          command: npm install

      - run:
          name: Run Node.js Tests
          command: npm test

      # Python API Build and Test
      - run:
          name: Install Python Dependencies
          command: |
            sudo apt-get install -y python3-pip
            pip3 install -r requirements.txt

      - run:
          name: Run Python Tests
          command: python3 -m unittest discover -s tests/

workflows:
  version: 2
  build:
    jobs:
      - build
