version: 2.1
orbs:
  node: circleci/node@5.1.0

filters:
  branches:
    only:
      - "*"  # run on all branches

jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install
          name: Install Node.js Dependencies
      - run:
          command: npm run test
          name: Run tests

workflows:
  version: 2
  test_my_app:
    jobs:
      - test
