version: 2.1

jobs:
  start-reactjs:
    steps:
      - checkout
      - run:
          name: Install Frontend Dependencies
          command: npm install
      - run:
          name: Start ReactJS
          command: npm start

  run-python-api:
    steps:
      - checkout
      - run:
          name: Start Python API
          command: python Api.py        

  run-pytest:
    steps:
      - checkout
      - run:
          name: Run Pytest
          command: pytest
          
  workflows:
  build-test-and-deploy-reactjs:
    jobs:
      - start-reactjs
      - run-python-api:
          requires:
            - start-reactjs
      - run-pytest:
          requires:
            - run-python-api

          
