version: 2.1

jobs:
  start-reactjs:
    steps:
      - checkout
      - run:
          name: Install Frontend Dependencies
          command: npm install
      - run:
          name: Start ReactJS
          command: npm start

  run-pytest:
    steps:
      - checkout
      - run:
          name: Run Pytest
          command: pytest
