version: 2.1

jobs:
  build-test-and-deploy-reactjs:
    steps:
      - checkout
      - run:
          name: Install Frontend Dependencies
          command: npm install
      - run:
          name: Start ReactJS
          command: npm start

  run-python-api:
    steps:
      - checkout
      - run:
          name: Start Python API
          command: python Api.py

  run-pytest:
    steps:
      - checkout
      - run:
          name: Run Pytest
          command: pytest

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build-test-and-deploy-reactjs
      - run-python-api:
          requires:
            - build-test-and-deploy-reactjs
      - run-pytest:
          requires:
            - build-test-and-deploy-reactjs
