version: 2.1
orbs:
  node: circleci/node@5.1.0

filters:
  branches:
    only:
      - "*"  # run on all branches

jobs:
  test:
    executor: node/default
    working_directory: /home/circleci/project/my-react  # Set the correct path to your project
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install Node.js Dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Start Server
          command: npm start

  backend_test:
    docker:
      - image: python:3.8  # Use a Python Docker image with the desired version
    working_directory: /home/circleci/project/my-react
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: pip install -r src/services/requirements.txt
      - run:
          name: Run Backend Tests
          command: pytest src/services/test_app.py

workflows:
  version: 2
  test_my_app:
    jobs:
      - test
      - backend_test:
          requires:
            - test
