version: 2.1
orbs:
  node: circleci/node@5.1.0

jobs:
  test:
    executor: node/default
    working_directory: /home/circleci/project/my-react
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install Node.js Dependencies
          command: npm install --legacy-peer-deps
      - run:
          name: Run Frontend Tests
          command: npm test
      - run:
          name: Start Frontend Server
          command: npm start
          background: true

  backend_test:
    docker:
      - image: python:3.8
    environment:
      API_PATH: /home/circleci/project/my-react/src/Services/Api.py
      TEST_PATH: /home/circleci/project/my-react/src/Services/test_app.py
    working_directory: /home/circleci/project/my-react
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            apt-get update && apt-get install -y unixodbc-dev
            pip install -r requirements.txt
      - run:
          name: Run API Server
          command: python $API_PATH
      - run:
          name: Run Backend Tests
          command: pytest $TEST_PATH

workflows:
  version: 2
  test_my_app:
    jobs:
      - test
      - backend_test:
          requires:
            - test
