version: 2.1
orbs:
  node: circleci/node@5.1.0

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - run: echo "hello world"
      - run:
          name: Install Node.js
          command: |
            sudo apt-get install -y nodejs
            sudo apt-get install -y npm
      - run:
          name: Debug
          command: ls /home/circleci/project/my-react
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install Node.js Dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Build app
          command: npm run build

workflows:
  version: 2
  test_my_app:
    jobs:
      - build_and_test
