version: 2.1
orbs:
  node: circleci/node@5.1.0

jobs:
  build_and_test:
    executor: node/default
    working_directory: /home/circleci/my-react  # Set the correct path to your project
    steps:
      - checkout
      - run:
          name: Install Node.js Dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  test_my_app:
    jobs:
      - build_and_test
